import {
  ChiliImg,
  DaalImg,
  FreshChiniguraChal,
  FreshRedSmallOnions,
  FreshShamratOnion,
  FreshThaiTomatoes,
  GarlicImg,
  GreenDeshiChili,
  LargeFreshGarlic,
  OnionImg,
  PotatoImg,
  RedLargeOnions,
  RiceImg,
  RoundLargePotatoes,
  SmallPotatos,
  TomatoImg,
} from "../assets";

const productCatagories = [
  {
    id: 1,
    name: "Tomato",
    image: TomatoImg,
  },
  {
    id: 2,
    name: "Potato",
    image: PotatoImg,
  },
  {
    id: 3,
    name: "Onion",
    image: OnionImg,
  },
  {
    id: 4,
    name: "Rice",
    image: RiceImg,
  },
  {
    id: 5,
    name: "Chili",
    image: ChiliImg,
  },
  {
    id: 6,
    name: "Garlic",
    image: GarlicImg,
  },
  {
    id: 7,
    name: "Daal",
    image: DaalImg,
  },
];

const products = [
  {
    id: 1,
    name: "Fresh Thai Tomatoes",
    catagory: 2,
    image: FreshThaiTomatoes,
    minQuantity: 20,
    maxQuantity: 800,
    location: "Rajshahi", //hubId 
    price: 117,
    shipping: 3,
  },
  {
    id: 2,
    name: "Round large potatoes",
    catagory: 2,
    image: RoundLargePotatoes,
    minQuantity: 50,
    maxQuantity: 1000,
    location: "Bogura", //hubId 
    price: 153,
    shipping: 3,
  },
  {
    id: 3,
    name: "Red large Onions",
    catagory: 2,
    image: RedLargeOnions,
    minQuantity: 15,
    maxQuantity: 600,
    location: "Rajbari", //hub id 
    price: 105,
    shipping: 2.5,
  },
  {
    id: 4,
    name: "Fresh Chinigura Chal",
    catagory: 3,
    image: FreshChiniguraChal,
    minQuantity: 10,
    maxQuantity: 400,
    location: "Mymensingh", //hubId 
    price: 149,
    shipping: 2,
  },
  {
    id: 5,
    name: "Green Deshi Chili",
    catagory: 6,
    image: GreenDeshiChili,
    minQuantity: 10,
    maxQuantity: 200,
    location: "Cuadanga", //hubId 
    price: 96,
    shipping: 1.5,
  },
  {
    id: 6,
    name: "Large Fresh Garlic",
    catagory: 4,
    image: LargeFreshGarlic,
    minQuantity: 20,
    maxQuantity: 600,
    location: "Rajbari", //hubId 
    price: 141,
    shipping: 2,
  },
  {
    id: 7,
    name: "Fresh Shamrat Onion",
    catagory: 3,
    image: FreshShamratOnion,
    minQuantity: 20,
    maxQuantity: 600,
    location: "Rajbari", //hubId 
    price: 115,
    shipping: 2,
  },
  {
    id: 8,
    name: "Small Potatos",
    catagory: 2,
    image: SmallPotatos,
    minQuantity: 20,
    maxQuantity: 600,
    location: "Rajbari", //hubId 
    price: 112,
    shipping: 2,
  },
  {
    id: 9,
    name: "Fresh Red Small Onions",
    catagory: 3,
    image: FreshRedSmallOnions,
    minQuantity: 20,
    maxQuantity: 600,
    location: "Rajbari", //hubId 
    price: 105,
    shipping: 2,
  },
];

const hubs = [
  {
    id: 1,
    name: "VeggieMart",
    subdistrict: "Baliakandi",
    district: "Rajbari",
    division: "Dhaka",
    location: "Rajbari, Dhaka",
  },
  {
    id: 2,
    name: "GreenLeaf",
    subdistrict: "Goalondo",
    district: "Rajbari",
    division: "Dhaka",
    location: "Rajbari, Dhaka",
  },
  {
    id: 3,
    name: "FreshPick",
    subdistrict: "Sadar",
    district: "Rajbari",
    division: "Dhaka",
    location: "Rajbari, Dhaka",
  },
  {
    id: 4,
    name: "VeggieTown",
    subdistrict: "Joydevpur",
    district: "Gazipur",
    division: "Dhaka",
    location: "Gazipur, Dhaka",
  },
  {
    id: 5,
    name: "LeafyMarket",
    subdistrict: "Kaliakair",
    district: "Gazipur",
    division: "Dhaka",
    location: "Gazipur, Dhaka",
  },
  {
    id: 6,
    name: "VeggieBox",
    subdistrict: "Sadar",
    district: "Narayanganj",
    division: "Dhaka",
    location: "Narayanganj, Dhaka",
  },
  {
    id: 7,
    name: "GreenGrove",
    subdistrict: "Bandhan",
    district: "Narayanganj",
    division: "Dhaka",
    location: "Narayanganj, Dhaka",
  },
  {
    id: 8,
    name: "VeggieMart",
    subdistrict: "Patenga",
    district: "Chittagong",
    division: "Chattogram",
    location: "Chittagong, Chattogram",
  },
  {
    id: 9,
    name: "GreenLeaf",
    subdistrict: "Foy's Lake",
    district: "Chittagong",
    division: "Chattogram",
    location: "Chittagong, Chattogram",
  },
  {
    id: 10,
    name: "FreshPick",
    subdistrict: "Cox's Bazar",
    district: "Cox's Bazar",
    division: "Chattogram",
    location: "Cox's Bazar, Chattogram",
  },
  {
    id: 11,
    name: "LeafyMarket",
    subdistrict: "Teknaf",
    district: "Cox's Bazar",
    division: "Chattogram",
    location: "Cox's Bazar, Chattogram",
  },
  {
    id: 12,
    name: "VeggieBox",
    subdistrict: "Sadar",
    district: "Khulna",
    division: "Khulna",
    location: "Khulna, Khulna",
  },
  {
    id: 13,
    name: "GreenGrove",
    subdistrict: "Dighalia",
    district: "Khulna",
    division: "Khulna",
    location: "Khulna, Khulna",
  },
  {
    id: 14,
    name: "VeggieMart",
    subdistrict: "Sadar",
    district: "Jessore",
    division: "Khulna",
    location: "Jessore, Khulna",
  },
  {
    id: 15,
    name: "GreenLeaf",
    subdistrict: "Chaugachha",
    district: "Jessore",
    division: "Khulna",
    location: "Jessore, Khulna",
  },
  {
    id: 16,
    name: "FreshPick",
    subdistrict: "Sadar",
    district: "Rajshahi",
    division: "Rajshahi",
    location: "Rajshahi, Rajshahi",
  },
  {
    id: 17,
    name: "LeafyMarket",
    subdistrict: "Mohanpur",
    district: "Rajshahi",
    division: "Rajshahi",
    location: "Rajshahi, Rajshahi",
  },
  {
    id: 18,
    name: "VeggieBox",
    subdistrict: "Sadar",
    district: "Bogura",
    division: "Rajshahi",
    location: "Bogura, Rajshahi",
  },
  {
    id: 19,
    name: "GreenGrove",
    subdistrict: "Shibganj",
    district: "Bogura",
    division: "Rajshahi",
    location: "Bogura, Rajshahi",
  },
  {
    id: 20,
    name: "VeggieMart",
    subdistrict: "Sadar",
    district: "Barishal",
    division: "Barishal",
    location: "Barishal, Barishal",
  },
  {
    id: 21,
    name: "GreenLeaf",
    subdistrict: "Muladi",
    district: "Barishal",
    division: "Barishal",
    location: "Barishal, Barishal",
  },
  {
    id: 22,
    name: "FreshPick",
    subdistrict: "Sadar",
    district: "Sylhet",
    division: "Sylhet",
    location: "Sylhet, Sylhet",
  },
  {
    id: 23,
    name: "LeafyMarket",
    subdistrict: "Moulvibazar",
    district: "Sylhet",
    division: "Sylhet",
    location: "Sylhet, Sylhet",
  },
  {
    id: 24,
    name: "VeggieBox",
    subdistrict: "Sadar",
    district: "Moulvibazar",
    division: "Sylhet",
    location: "Moulvibazar, Sylhet",
  },
  {
    id: 25,
    name: "GreenGrove",
    subdistrict: "Kulaura",
    district: "Moulvibazar",
    division: "Sylhet",
    location: "Moulvibazar, Sylhet",
  },
  {
    id: 26,
    name: "VeggieMart",
    subdistrict: "Sadar",
    district: "Mymensingh",
    division: "Mymensingh",
    location: "Mymensingh, Mymensingh",
  },
  {
    id: 27,
    name: "GreenLeaf",
    subdistrict: "Trishal",
    district: "Mymensingh",
    division: "Mymensingh",
    location: "Mymensingh, Mymensingh",
  },
  {
    id: 28,
    name: "FreshPick",
    subdistrict: "Sadar",
    district: "Jamalpur",
    division: "Mymensingh",
    location: "Jamalpur, Mymensingh",
  },
  {
    id: 29,
    name: "LeafyMarket",
    subdistrict: "Baksiganj",
    district: "Jamalpur",
    division: "Mymensingh",
    location: "Jamalpur, Mymensingh",
  },
  {
    id: 30,
    name: "VeggieBox",
    subdistrict: "Sadar",
    district: "Rangpur",
    division: "Rangpur",
    location: "Rangpur, Rangpur",
  },
  {
    id: 31,
    name: "GreenGrove",
    subdistrict: "Kurigram",
    district: "Rangpur",
    division: "Rangpur",
    location: "Rangpur, Rangpur",
  },
  {
    id: 32,
    name: "VeggieMart",
    subdistrict: "Sadar",
    district: "Dinajpur",
    division: "Rangpur",
    location: "Dinajpur, Rangpur",
  },
  {
    id: 33,
    name: "GreenLeaf",
    subdistrict: "Birampur",
    district: "Dinajpur",
    division: "Rangpur",
    location: "Dinajpur, Rangpur",
  },
];


export { products, hubs, productCatagories };
